CREATE TABLE shop_customers (
    id    uuid PRIMARY KEY,
    name  text NOT NULL,
    email text NOT NULL UNIQUE
);

CREATE TABLE shop_orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id uuid          NOT NULL REFERENCES shop_customers (id),
    total       numeric(10, 2) NOT NULL
);
