CREATE TYPE lib_genre AS ENUM ('fiction', 'non-fiction');

CREATE TABLE lib_books (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     text      NOT NULL,
    genre     lib_genre NOT NULL,
    published date
);
