plugins {
    id("lxrin.java-conventions")
    `java-test-fixtures`
    id("lxrin.publish-conventions")
}

description = "LxrinQL core: a strongly typed query language and data access layer for PostgreSQL. No runtime dependencies."

dependencies {
    testFixturesImplementation(platform(libs.junit.bom))
    testFixturesImplementation(libs.junit.jupiter.api)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.launcher)
}

// Test fixtures (hand-written tables, recording executor) are shared with the integration tests, not published.
val javaComponent = components["java"] as AdhocComponentWithVariants
javaComponent.withVariantsFromConfiguration(configurations["testFixturesApiElements"]) { skip() }
javaComponent.withVariantsFromConfiguration(configurations["testFixturesRuntimeElements"]) { skip() }

tasks.jar {
    manifest {
        attributes("Automatic-Module-Name" to "ch.lxrin.ql.core")
    }
}

// -----------------------------------------------------------------------------
// Arity-specific classes (Row1..16, Mapper1..16, Select1..16, InsertValues1..16
// and the select/returning overloads) are generated from templates.
// -----------------------------------------------------------------------------

val maxArity = 16
val generatedArityDir = layout.buildDirectory.dir("generated/sources/arity/java/main")

val generateArity by tasks.registering(GenerateArity::class) {
    arity.set(maxArity)
    outputDir.set(generatedArityDir)
}

sourceSets.main {
    java.srcDir(generateArity)
}

abstract class GenerateArity : DefaultTask() {
    @get:Input
    abstract val arity: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = outputDir.get().asFile
        root.deleteRecursively()
        val dsl = File(root, "ch/lxrin/ql/dsl").apply { mkdirs() }
        val runtime = File(root, "ch/lxrin/ql/runtime").apply { mkdirs() }
        val max = arity.get()
        fun tps(n: Int) = (1..n).joinToString(", ") { "T$it" }
        fun header(pkg: String) = "package $pkg;\n\n// Generated by the generateArity task – do not edit.\n\n"

        for (n in 1..max) {
            val t = tps(n)
            // Row
            File(dsl, "Row$n.java").writeText(header("ch.lxrin.ql.dsl") + """
/**
 * A typed result tuple with $n value${if (n > 1) "s" else ""}.
 *
${(1..n).joinToString("\n") { " * @param value$it value $it" }}
${(1..n).joinToString("\n") { " * @param <T$it> type of value $it" }}
 */
public record Row$n<$t>(${(1..n).joinToString(", ") { "T$it value$it" }}) {

    /** Maps this tuple, e.g. to a record: {@code row.map(UserSummary::new)}. */
    public <R> R map(Mapper$n<${(1..n).joinToString(", ") { "? super T$it" }}, ? extends R> mapper) {
        return mapper.map(${(1..n).joinToString(", ") { "value$it" }});
    }
}
""".trimStart())
            // Mapper
            File(dsl, "Mapper$n.java").writeText(header("ch.lxrin.ql.dsl") + """
/**
 * Maps $n typed values to an object; usually a constructor reference such as {@code UserSummary::new}.
 *
${(1..n).joinToString("\n") { " * @param <T$it> type of value $it" }}
 * @param <R> result type
 */
@FunctionalInterface
public interface Mapper$n<$t, R> {

    /** Maps the values. */
    R map(${(1..n).joinToString(", ") { "T$it value$it" }});
}
""".trimStart())
            // Select
            val casts = (1..n).joinToString(", ") { "(T$it) v[${it - 1}]" }
            if (n == 1) {
                File(dsl, "Select1.java").writeText(header("ch.lxrin.ql.dsl") + """
import ch.lxrin.ql.runtime.QueryContext;

import java.util.List;
import java.util.Optional;
import java.util.function.Function;

/**
 * A {@code SELECT} of one field; rows are returned as plain values.
 * It can be used as a sub-query ({@code IN}, {@code EXISTS}, scalar).
 *
 * @param <T1> the field type
 */
public final class Select1<T1> extends AbstractSelect<T1, Select1<T1>> implements Subquery<T1> {

    private final Field<T1> field1;

    /** Creates the select; use {@code Dsl.select(field)} or {@code ctx.select(field)}. */
    public Select1(QueryContext context, Field<T1> f1) {
        super(context, List.of(f1));
        this.field1 = f1;
    }

    @Override
    @SuppressWarnings("unchecked")
    protected T1 map(Object[] v) {
        return (T1) v[0];
    }

    /** Executes the query and maps every value. */
    public <R> List<R> fetch(Function<? super T1, ? extends R> mapper) {
        return fetchMapped(mapper);
    }

    /** Returns the sub-query as a scalar expression: {@code (SELECT ...)}. */
    @Override
    public Field<T1> asField() {
        return Fields.of(field1.type(), this);
    }

    /** Returns the first value, if any, without checking for more rows. */
    public Optional<T1> fetchFirstValue() {
        return fetchFirst();
    }
}
""".trimStart())
            } else {
                File(dsl, "Select$n.java").writeText(header("ch.lxrin.ql.dsl") + """
import ch.lxrin.ql.runtime.QueryContext;

import java.util.List;
import java.util.Optional;

/**
 * A {@code SELECT} of $n fields; rows are {@link Row$n} tuples, or your own
 * type through {@link #fetch(Mapper$n)}, e.g. {@code fetch(UserSummary::new)}.
 *
${(1..n).joinToString("\n") { " * @param <T$it> type of field $it" }}
 */
public final class Select$n<$t> extends AbstractSelect<Row$n<$t>, Select$n<$t>> {

    /** Creates the select; use {@code Dsl.select(..)} or {@code ctx.select(..)}. */
    public Select$n(QueryContext context, ${(1..n).joinToString(", ") { "Field<T$it> f$it" }}) {
        super(context, List.of(${(1..n).joinToString(", ") { "f$it" }}));
    }

    @Override
    @SuppressWarnings("unchecked")
    protected Row$n<$t> map(Object[] v) {
        return new Row$n<>($casts);
    }

    /** Executes the query and maps every row, e.g. {@code fetch(UserSummary::new)}. */
    public <R> List<R> fetch(Mapper$n<${(1..n).joinToString(", ") { "? super T$it" }}, ? extends R> mapper) {
        return fetchMapped(row -> row.map(mapper));
    }

    /** Executes the query, expects exactly one row and maps it. */
    public <R> R fetchOne(Mapper$n<${(1..n).joinToString(", ") { "? super T$it" }}, ? extends R> mapper) {
        return fetchOne().map(mapper);
    }

    /** Executes the query, expects at most one row and maps it. */
    public <R> Optional<R> fetchOptional(Mapper$n<${(1..n).joinToString(", ") { "? super T$it" }}, ? extends R> mapper) {
        return fetchOptional().map(row -> row.map(mapper));
    }
}
""".trimStart())
            }
            // InsertValues
            val cols = (1..n).joinToString(", ") { "Column<T$it> c$it" }
            val selectType = if (n == 1) "Select1<T1>" else "Select$n<$t>"
            File(dsl, "InsertValues$n.java").writeText(header("ch.lxrin.ql.dsl") + """
import ch.lxrin.ql.runtime.QueryContext;
import ch.lxrin.ql.schema.Column;
import ch.lxrin.ql.schema.Table;

import java.util.List;
import java.util.Map;

/**
 * An {@code INSERT} with $n typed columns: {@code insertInto(T).columns(..).values(..).values(..)}.
 *
 * @param <R> the table's row type
${(1..n).joinToString("\n") { " * @param <T$it> type of column $it" }}
 */
public final class InsertValues$n<R, $t> extends AbstractInsert<R, InsertValues$n<R, $t>> {

${(1..n).joinToString("\n") { "    private final Column<T$it> c$it;" }}

    InsertValues$n(QueryContext context, Table<R> table, $cols) {
        super(context, table);
${(1..n).joinToString("\n") { "        this.c$it = c$it;" }}
    }

    /** Adds a row of values; {@code null} inserts {@code NULL}. */
    public InsertValues$n<R, $t> values(${(1..n).joinToString(", ") { "T$it v$it" }}) {
        Map<Column<?>, Field<?>> row = statement.addRow();
${(1..n).joinToString("\n") { "        row.put(c$it, Values.param(v$it, c$it.type()));" }}
        return this;
    }

    /** Adds a row of expressions. */
    public InsertValues$n<R, $t> values(${(1..n).joinToString(", ") { "Field<T$it> v$it" }}) {
        Map<Column<?>, Field<?>> row = statement.addRow();
${(1..n).joinToString("\n") { "        row.put(c$it, require(v$it));" }}
        return this;
    }

    /** {@code INSERT INTO t (columns) SELECT ...} with a query of matching types. */
    public InsertValues$n<R, $t> select($selectType query) {
        statement.source(List.of(${(1..n).joinToString(", ") { "c$it" }}), query.statement());
        return this;
    }
}
""".trimStart())
        }

        // Static select overloads for Dsl
        File(dsl, "ArityStatics.java").writeText(header("ch.lxrin.ql.dsl") + """
/** The typed {@code select(..)} overloads of {@link Dsl}; statements run on the default query context. */
public class ArityStatics {

    /** Static members only. */
    protected ArityStatics() {}
${(1..max).joinToString("") { n -> """
    /** {@code SELECT} of $n field${if (n > 1) "s" else ""}. */
    public static <${tps(n)}> ${if (n == 1) "Select1<T1>" else "Select$n<${tps(n)}>"} select(${(1..n).joinToString(", ") { "Field<T$it> f$it" }}) {
        return new Select$n<>(null, ${(1..n).joinToString(", ") { "f$it" }});
    }
""" }}}
""".trimStart())

        // Instance select overloads for QueryContext
        File(runtime, "ArityContextBase.java").writeText(header("ch.lxrin.ql.runtime") + """
import ch.lxrin.ql.dsl.*;

/** The typed {@code select(..)} overloads of {@link QueryContext}. */
public abstract class ArityContextBase {

    ArityContextBase() {}

    /** Returns the context the statements are attached to. */
    abstract QueryContext self();
${(1..max).joinToString("") { n -> """
    /** {@code SELECT} of $n field${if (n > 1) "s" else ""}, attached to this context. */
    public <${tps(n)}> ${if (n == 1) "Select1<T1>" else "Select$n<${tps(n)}>"} select(${(1..n).joinToString(", ") { "Field<T$it> f$it" }}) {
        return new Select$n<>(self(), ${(1..n).joinToString(", ") { "f$it" }});
    }
""" }}}
""".trimStart())

        // columns(..) overloads of an INSERT
        File(dsl, "InsertColumns.java").writeText(header("ch.lxrin.ql.dsl") + """
import ch.lxrin.ql.runtime.QueryContext;
import ch.lxrin.ql.schema.Column;
import ch.lxrin.ql.schema.Table;

/**
 * The typed {@code columns(..)} overloads of {@link Insert}.
 *
 * @param <R> the table's row type
 */
public abstract class InsertColumns<R> extends AbstractInsert<R, Insert<R>> {

    InsertColumns(QueryContext context, Table<R> table) {
        super(context, table);
    }
${(1..max).joinToString("") { n -> """
    /** Starts a multi-row insert with $n typed column${if (n > 1) "s" else ""}; continue with {@code values(..)} or {@code select(..)}. */
    public <${tps(n)}> InsertValues$n<R, ${tps(n)}> columns(${(1..n).joinToString(", ") { "Column<T$it> c$it" }}) {
        requireEmpty();
        return new InsertValues$n<>(attachedContext(), table(), ${(1..n).joinToString(", ") { "c$it" }});
    }
""" }}}
""".trimStart())

        // returning(..) overloads of INSERT/UPDATE/DELETE
        File(dsl, "DmlReturningBase.java").writeText(header("ch.lxrin.ql.dsl") + """
import java.util.List;
import java.util.function.Function;

/** The typed {@code returning(..)} overloads of {@code INSERT}, {@code UPDATE} and {@code DELETE}. */
public abstract class DmlReturningBase {

    DmlReturningBase() {}

    /** Adds {@code RETURNING} fields and returns the executable statement. */
    abstract <X> Returning<X> returningFields(List<Field<?>> fields, Function<Object[], X> mapper);

    /** {@code RETURNING field}; rows are plain values. */
    @SuppressWarnings("unchecked")
    public <T1> Returning<T1> returning(Field<T1> f1) {
        return returningFields(List.of(f1), v -> (T1) v[0]);
    }
${(2..max).joinToString("") { n -> """
    /** {@code RETURNING} $n fields; rows are {@link Row$n} tuples. */
    @SuppressWarnings("unchecked")
    public <${tps(n)}> Returning<Row$n<${tps(n)}>> returning(${(1..n).joinToString(", ") { "Field<T$it> f$it" }}) {
        return returningFields(List.of(${(1..n).joinToString(", ") { "f$it" }}), v -> new Row$n<>(${(1..n).joinToString(", ") { "(T$it) v[${it - 1}]" }}));
    }
""" }}}
""".trimStart())
    }
}
