CREATE TABLE asset (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        uuid REFERENCES app_user (id),
    name            text          NOT NULL,
    classification  text          NOT NULL DEFAULT 'internal'
        CONSTRAINT asset_classification_check CHECK (classification IN ('public', 'internal', 'confidential', 'secret')),
    value           numeric(12, 2),
    organization_id uuid          NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    created_by      text,
    updated_at      timestamptz,
    updated_by      text,
    deleted_at      timestamptz,
    version         bigint        NOT NULL DEFAULT 0,
    CONSTRAINT asset_org_name_key UNIQUE (organization_id, name)
);

CREATE TABLE risk (
    asset_id   bigint  NOT NULL REFERENCES asset (id),
    threat     text    NOT NULL,
    likelihood integer NOT NULL,
    impact     integer NOT NULL,
    score      integer GENERATED ALWAYS AS (likelihood * impact) STORED,
    PRIMARY KEY (asset_id, threat)
);

CREATE TABLE event_log (
    id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message text NOT NULL
);

CREATE VIEW active_user AS
    SELECT id, name, email, organization_id FROM app_user WHERE deleted_at IS NULL;
