-- Bookings of assets: ranges, full-text search, integer arrays and JSON for the operator tests of 3.1.

CREATE TABLE booking (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id   bigint    NOT NULL REFERENCES asset (id),
    period     tstzrange NOT NULL,
    days       daterange,
    note       text      NOT NULL DEFAULT '',
    search     tsvector GENERATED ALWAYS AS (to_tsvector('english', note)) STORED,
    slots      integer[] NOT NULL DEFAULT '{}',
    attributes jsonb     NOT NULL DEFAULT '{}'
);

COMMENT ON TABLE booking IS 'Reservations of assets';
