-- The audit history in the layout of Hibernate Envers, written by lxrin-ql-audit. It replaces the hand-written
-- layout of V3: rev and revtype (0 insert, 1 update, 2 delete), primary key (id, rev), one revision per transaction.
DROP TABLE app_user_aud;
DROP TABLE asset_aud;
DROP TABLE revision;

CREATE TABLE revision (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revised_at timestamptz NOT NULL,
    user_id    uuid
);

-- not audited: changes on every sign-in
ALTER TABLE app_user ADD COLUMN last_seen_at timestamptz;

CREATE TABLE app_user_aud (
    id              uuid     NOT NULL,
    rev             bigint   NOT NULL REFERENCES revision (id),
    revtype         smallint NOT NULL,
    name            text,
    email           text,
    role            app_role,
    active          boolean,
    tags            text[],
    settings        jsonb,
    organization_id uuid,
    created_at      timestamptz,
    created_by      text,
    updated_at      timestamptz,
    updated_by      text,
    deleted_at      timestamptz,
    version         bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE asset_aud (
    id              bigint   NOT NULL,
    rev             bigint   NOT NULL REFERENCES revision (id),
    revtype         smallint NOT NULL,
    owner_id        uuid,
    name            text,
    classification  text,
    value           numeric(12, 2),
    organization_id uuid,
    created_at      timestamptz,
    created_by      text,
    updated_at      timestamptz,
    updated_by      text,
    deleted_at      timestamptz,
    version         bigint,
    PRIMARY KEY (id, rev)
);

-- Written by both Hibernate (with Envers) and LxrinQL in EnversIT.
CREATE TABLE note (
    id    uuid PRIMARY KEY,
    title text NOT NULL,
    body  text
);

CREATE TABLE note_aud (
    id      uuid     NOT NULL,
    rev     bigint   NOT NULL REFERENCES revision (id),
    revtype smallint NOT NULL,
    title   text,
    body    text,
    PRIMARY KEY (id, rev)
);
