package ch.lxrin.ql.spring;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Configuration properties {@code lxrin.ql.audit.*} of the audit history ({@code lxrin-ql-audit}).
 * The audit listener is created when {@code tables} or {@code table-patterns} is set.
 */
@ConfigurationProperties("lxrin.ql.audit")
public class LxrinQlAuditProperties {

    /** Whether the audit history is written when tables are configured. */
    private boolean enabled = true;
    /** Audited tables, by name or schema-qualified name. */
    private List<String> tables = new ArrayList<>();
    /** Regular expressions of audited table names. */
    private List<String> tablePatterns = new ArrayList<>();
    /** Columns not copied to the audit table, per table, e.g. {@code excluded-columns.app_user=last_seen_at}. */
    private Map<String, List<String>> excludedColumns = new LinkedHashMap<>();
    /** Suffix of the audit tables. */
    private String suffix = "_aud";
    /** Whether delete rows contain the full row instead of only the key. */
    private boolean storeDataAtDelete = false;
    /** Revision column of the audit tables. */
    private String revColumn = "rev";
    /** Revision type column of the audit tables. */
    private String revtypeColumn = "revtype";
    /** The revision table. */
    private final Revision revision = new Revision();

    /** Returns whether auditing is enabled. */
    public boolean isEnabled() {
        return enabled;
    }

    /** Enables or disables auditing. */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /** Returns the audited tables. */
    public List<String> getTables() {
        return tables;
    }

    /** Sets the audited tables. */
    public void setTables(List<String> tables) {
        this.tables = tables;
    }

    /** Returns the table patterns. */
    public List<String> getTablePatterns() {
        return tablePatterns;
    }

    /** Sets the table patterns. */
    public void setTablePatterns(List<String> tablePatterns) {
        this.tablePatterns = tablePatterns;
    }

    /** Returns the excluded columns per table. */
    public Map<String, List<String>> getExcludedColumns() {
        return excludedColumns;
    }

    /** Sets the excluded columns per table. */
    public void setExcludedColumns(Map<String, List<String>> excludedColumns) {
        this.excludedColumns = excludedColumns;
    }

    /** Returns the audit table suffix. */
    public String getSuffix() {
        return suffix;
    }

    /** Sets the audit table suffix. */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /** Returns whether delete rows contain the full row. */
    public boolean isStoreDataAtDelete() {
        return storeDataAtDelete;
    }

    /** Sets whether delete rows contain the full row. */
    public void setStoreDataAtDelete(boolean storeDataAtDelete) {
        this.storeDataAtDelete = storeDataAtDelete;
    }

    /** Returns the revision column. */
    public String getRevColumn() {
        return revColumn;
    }

    /** Sets the revision column. */
    public void setRevColumn(String revColumn) {
        this.revColumn = revColumn;
    }

    /** Returns the revision type column. */
    public String getRevtypeColumn() {
        return revtypeColumn;
    }

    /** Sets the revision type column. */
    public void setRevtypeColumn(String revtypeColumn) {
        this.revtypeColumn = revtypeColumn;
    }

    /** Returns the revision table settings. */
    public Revision getRevision() {
        return revision;
    }

    /** The revision table: one row per transaction. */
    public static class Revision {
        /** Schema of the revision table; the default schema if empty. */
        private String schema;
        /** Name of the revision table. */
        private String table = "revision";
        /** Revision number column, generated by the database. */
        private String idColumn = "id";
        /** Revision timestamp column. */
        private String timestampColumn = "revised_at";
        /** Revision user column, written when an AuditUser bean exists. */
        private String userColumn = "user_id";

        /** Returns the schema. */
        public String getSchema() {
            return schema;
        }

        /** Sets the schema. */
        public void setSchema(String schema) {
            this.schema = schema;
        }

        /** Returns the table. */
        public String getTable() {
            return table;
        }

        /** Sets the table. */
        public void setTable(String table) {
            this.table = table;
        }

        /** Returns the id column. */
        public String getIdColumn() {
            return idColumn;
        }

        /** Sets the id column. */
        public void setIdColumn(String idColumn) {
            this.idColumn = idColumn;
        }

        /** Returns the timestamp column. */
        public String getTimestampColumn() {
            return timestampColumn;
        }

        /** Sets the timestamp column. */
        public void setTimestampColumn(String timestampColumn) {
            this.timestampColumn = timestampColumn;
        }

        /** Returns the user column. */
        public String getUserColumn() {
            return userColumn;
        }

        /** Sets the user column. */
        public void setUserColumn(String userColumn) {
            this.userColumn = userColumn;
        }
    }
}
