package ch.lxrin.ql.codegen;

import ch.lxrin.ql.codegen.SchemaModel.ColumnModel;
import ch.lxrin.ql.codegen.SchemaModel.EnumModel;
import ch.lxrin.ql.codegen.SchemaModel.ForeignKeyModel;
import ch.lxrin.ql.codegen.SchemaModel.KeyModel;
import ch.lxrin.ql.codegen.SchemaModel.TableModel;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Generates Java sources from a PostgreSQL schema. For every table:
 * <ul>
 *   <li>a table class ({@code UserTable} with the constant {@code USERS}) with typed columns and keys,</li>
 *   <li>a row record ({@code UserRow}),</li>
 *   <li>an entity ({@code User}) and a repository base class ({@code UserRepositoryBase}),</li>
 *   <li>once, a hand-written repository subclass ({@code UserRepository}) that is never overwritten.</li>
 * </ul>
 * Views and tables without primary key get a read-only repository and no entity.
 * PostgreSQL enums become Java enums unless they are mapped to existing ones.
 */
public final class CodeGenerator {

    static final String HEADER = "// Generated by LxrinQL codegen – do not edit.\n";
    private static final Pattern TYPE_MARKER = Pattern.compile("#([A-Za-z0-9_.$]+)#");

    /**
     * The files written by a run.
     *
     * @param generated the generated sources and resources
     * @param stubs     the repository subclasses created in the stub directory
     */
    public record Result(List<Path> generated, List<Path> stubs) {
    }

    private final CodegenConfig config;
    private final NamingStrategy naming;
    private final SchemaModel model;
    private final TypeMapping types;
    private final Map<TableModel, String> entityNames = new LinkedHashMap<>();
    private final Set<String> localNames = new HashSet<>();
    private final List<Path> generated = new ArrayList<>();
    private final List<Path> stubs = new ArrayList<>();

    private CodeGenerator(SchemaModel model, CodegenConfig config, NamingStrategy naming) {
        this.config = config.validate();
        this.naming = naming;
        this.model = model;
        this.types = new TypeMapping(config, model.enums(), naming);
    }

    /** Reads the schema through {@code connection} and generates the sources. */
    public static Result generate(Connection connection, CodegenConfig config) throws SQLException {
        return generate(SchemaReader.read(connection, config.validate()), config, new DefaultNamingStrategy(config));
    }

    /** Generates the sources for a schema model with a custom naming strategy. */
    public static Result generate(SchemaModel model, CodegenConfig config, NamingStrategy naming) {
        return new CodeGenerator(model, config, naming).run();
    }

    private Result run() {
        Map<String, TableModel> byEntity = new HashMap<>();
        for (TableModel t : model.tables()) {
            String entity = naming.entityName(t);
            TableModel previous = byEntity.put(entity, t);
            if (previous != null) {
                throw new IllegalStateException("tables " + previous.name() + " and " + t.name() + " both map to " + entity
                        + "; configure entityName(..) for one of them");
            }
            entityNames.put(t, entity);
            localNames.add(entity);
            localNames.add(entity + "Table");
            localNames.add(entity + "Row");
            localNames.add(entity + "Key");
            localNames.add(entity + "RepositoryBase");
            localNames.add(entity + "Repository");
        }
        localNames.add("Tables");
        for (EnumModel e : model.enums()) if (!types.mapped(e)) localNames.add(naming.enumName(e));

        Path packageDir = config.outputDirectory().resolve(config.packageName().replace('.', '/'));
        List<Path> previous = previouslyGenerated(packageDir);
        for (EnumModel e : usedEnums()) if (!types.mapped(e)) write(packageDir, naming.enumName(e), enumSource(e));
        List<String> repositories = new ArrayList<>();
        for (TableModel t : model.tables()) {
            String entity = entityNames.get(t);
            List<Col> cols = columns(t);
            write(packageDir, entity + "Table", tableSource(t, entity, cols));
            write(packageDir, entity + "Row", rowSource(t, entity, cols));
            boolean writable = !t.view() && t.primaryKey() != null;
            if (writable && t.primaryKey().columns().size() > 1) write(packageDir, entity + "Key", keySource(t, entity, cols));
            if (writable && config.generateEntities()) write(packageDir, entity, entitySource(t, entity, cols));
            if (config.generateRepositories()) {
                write(packageDir, entity + "RepositoryBase", writable ? repositoryBaseSource(t, entity, cols) : readOnlyBaseSource(t, entity));
                repositories.add(config.packageName() + "." + entity + "Repository");
                writeStub(entity, writable && config.generateEntities() ? entity : entity + "Row");
            }
        }
        write(packageDir, "Tables", tablesSource());
        if (config.resourcesDirectory() != null && !repositories.isEmpty()) {
            Path index = config.resourcesDirectory().resolve("META-INF/lxrin-ql/repositories");
            writeFile(index, String.join("\n", repositories) + "\n");
        }
        for (Path stale : previous) {
            if (!generated.contains(stale)) {
                try {
                    Files.deleteIfExists(stale);
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            }
        }
        return new Result(List.copyOf(generated), List.copyOf(stubs));
    }

    // =========================================================================
    // Columns
    // =========================================================================

    /** A column with its Java names and type. */
    private record Col(ColumnModel model, TypeMapping.Mapped type, String constant, String property, boolean pk) {
        String getter() {
            return "get" + Character.toUpperCase(property.charAt(0)) + property.substring(1);
        }

        String setter() {
            return "set" + Character.toUpperCase(property.charAt(0)) + property.substring(1);
        }
    }

    private List<Col> columns(TableModel t) {
        Set<String> reserved = new HashSet<>(Set.of("PK"));
        reserved.add(naming.tableConstant(t));
        List<Col> result = new ArrayList<>();
        Set<String> properties = new HashSet<>();
        for (ColumnModel c : t.columns()) {
            String constant = naming.columnConstant(c);
            while (reserved.contains(constant)) constant = constant + "_COLUMN";
            reserved.add(constant);
            String property = naming.property(c);
            while (!properties.add(property)) property = property + "_";
            boolean pk = t.primaryKey() != null && t.primaryKey().columns().contains(c.name());
            result.add(new Col(c, types.map(t, c), constant, property, pk));
        }
        return result;
    }

    private Col column(List<Col> cols, String name) {
        for (Col c : cols) if (c.model().name().equals(name)) return c;
        throw new IllegalStateException("unknown column " + name);
    }

    // =========================================================================
    // Table class
    // =========================================================================

    private String tableSource(TableModel t, String entity, List<Col> cols) {
        Imports imp = new Imports(config.packageName(), localNames);
        String cls = entity + "Table";
        String row = entity + "Row";
        StringBuilder b = new StringBuilder();
        b.append("/**\n * The ").append(t.view() ? "view" : "table").append(" {@code ").append(doc(qualified(t))).append("}.");
        comment(b, t.comment(), " * ");
        b.append("\n */\n");
        b.append("public final class ").append(cls).append(" extends ").append(imp.use("ch.lxrin.ql.schema.Table")).append('<').append(row).append("> {\n\n");
        b.append("    /** The ").append(t.view() ? "view" : "table").append(" without alias. */\n");
        b.append("    public static final ").append(cls).append(' ').append(naming.tableConstant(t)).append(" = new ").append(cls).append("(null);\n\n");
        String columnClass = imp.use("ch.lxrin.ql.schema.Column");
        for (Col c : cols) {
            b.append("    /** Column {@code ").append(doc(c.model().name())).append("}");
            if (c.model().comment() != null) b.append(": ").append(doc(c.model().comment()));
            b.append(". */\n");
            String fieldType = imp.use(c.type().fieldType()) + (c.type().typeArg() == null ? "" : "<" + boxed(imp, c.type().typeArg()) + ">");
            b.append("    public final ").append(fieldType).append(' ').append(c.constant()).append(" = ").append(c.type().factory())
                    .append("(\"").append(TypeMapping.escape(c.model().name())).append("\", ").append(resolve(imp, c.type().dataType()))
                    .append(", ").append(flags(columnClass, c)).append(");\n");
        }
        if (t.primaryKey() != null && !t.view()) {
            b.append('\n');
            KeyModel pk = t.primaryKey();
            String keyStrategy = imp.use("ch.lxrin.ql.schema.KeyStrategy");
            String pkClass = imp.use("ch.lxrin.ql.schema.PrimaryKey");
            if (pk.columns().size() == 1) {
                Col c = column(cols, pk.columns().get(0));
                b.append("    /** The primary key {@code ").append(doc(pk.name())).append("}. */\n");
                b.append("    public final ").append(pkClass).append('<').append(boxed(imp, c.type().javaType())).append("> PK = primaryKey(\"")
                        .append(TypeMapping.escape(pk.name())).append("\", ").append(c.constant()).append(", ")
                        .append(keyStrategy).append('.').append(strategy(c)).append(");\n");
            } else {
                String key = entity + "Key";
                StringBuilder from = new StringBuilder();
                StringBuilder to = new StringBuilder();
                StringBuilder colList = new StringBuilder();
                for (int i = 0; i < pk.columns().size(); i++) {
                    Col c = column(cols, pk.columns().get(i));
                    if (i > 0) {
                        from.append(", ");
                        to.append(", ");
                        colList.append(", ");
                    }
                    from.append('(').append(boxed(imp, c.type().javaType())).append(") v[").append(i).append(']');
                    to.append("k.").append(c.property()).append("()");
                    colList.append(c.constant());
                }
                b.append("    /** The primary key {@code ").append(doc(pk.name())).append("}. */\n");
                b.append("    public final ").append(pkClass).append('<').append(key).append("> PK = primaryKey(\"").append(TypeMapping.escape(pk.name()))
                        .append("\", ").append(key).append(".class, v -> new ").append(key).append('(').append(from)
                        .append("), k -> new Object[]{").append(to).append("}, ").append(colList).append(");\n");
            }
        }
        Set<String> keyNames = new HashSet<>();
        for (KeyModel uk : t.uniqueKeys()) {
            String name = uniqueName("UK_" + Names.upperSnake(String.join("_", uk.columns())), keyNames);
            b.append("    /** The unique key {@code ").append(doc(uk.name())).append("}. */\n");
            b.append("    public final ").append(imp.use("ch.lxrin.ql.schema.UniqueKey")).append(' ').append(name).append(" = uniqueKey(\"")
                    .append(TypeMapping.escape(uk.name())).append('"');
            for (String c : uk.columns()) b.append(", ").append(column(cols, c).constant());
            b.append(");\n");
        }
        for (ForeignKeyModel fk : t.foreignKeys()) {
            String base = "FK_" + referencedConstant(fk);
            String name = keyNames.contains(base) ? uniqueName("FK_" + Names.upperSnake(String.join("_", fk.columns())), keyNames)
                    : uniqueName(base, keyNames);
            b.append("    /** The foreign key {@code ").append(doc(fk.name())).append("} to {@code ").append(doc(fk.referencedTable())).append("}. */\n");
            String list = imp.use("java.util.List");
            b.append("    public final ").append(imp.use("ch.lxrin.ql.schema.ForeignKey")).append(' ').append(name).append(" = foreignKey(\"")
                    .append(TypeMapping.escape(fk.name())).append("\", ").append(list).append(".of(");
            for (int i = 0; i < fk.columns().size(); i++) {
                if (i > 0) b.append(", ");
                b.append(column(cols, fk.columns().get(i)).constant());
            }
            b.append("), ").append(schemaLiteral(fk.referencedSchema())).append(", \"").append(TypeMapping.escape(fk.referencedTable()))
                    .append("\", ").append(list).append(".of(");
            for (int i = 0; i < fk.referencedColumns().size(); i++) {
                if (i > 0) b.append(", ");
                b.append('"').append(TypeMapping.escape(fk.referencedColumns().get(i))).append('"');
            }
            b.append("));\n");
        }
        b.append("\n    /**\n     * Creates the table with an alias.\n     *\n     * @param alias the alias, or {@code null}\n     */\n");
        b.append("    public ").append(cls).append("(String alias) {\n        super(").append(schemaLiteral(t.schema())).append(", \"")
                .append(TypeMapping.escape(t.name())).append("\", alias);\n    }\n\n");
        b.append("    @Override\n    public ").append(cls).append(" as(String alias) {\n        return new ").append(cls).append("(alias);\n    }\n\n");
        b.append("    @Override\n    public ").append(row).append(" mapRow(").append(imp.use("ch.lxrin.ql.dsl.Row")).append(" row) {\n        return new ")
                .append(row).append('(');
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) b.append(", ");
            b.append("row.get(").append(cols.get(i).constant()).append(')');
        }
        b.append(");\n    }\n");
        if (t.view()) b.append("\n    @Override\n    public boolean readOnly() {\n        return true;\n    }\n");
        b.append("}\n");
        return file(imp, b);
    }

    private String strategy(Col c) {
        if (c.model().sequence() != null) return "sequence(\"" + TypeMapping.escape(c.model().sequence()) + "\")";
        if (!c.model().array() && "uuid".equals(c.model().type())) return "uuidV7()";
        return "none()";
    }

    private String flags(String columnClass, Col c) {
        List<String> flags = new ArrayList<>();
        ColumnModel m = c.model();
        if (m.notNull()) flags.add("NOT_NULL");
        if (m.hasDefault()) flags.add("DEFAULT");
        if ("d".equals(m.identity())) flags.add("IDENTITY");
        if ("a".equals(m.identity())) flags.add("IDENTITY_ALWAYS");
        if ("s".equals(m.generated())) flags.add("GENERATED");
        if (c.pk()) flags.add("PRIMARY_KEY");
        if (flags.isEmpty()) return "0";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < flags.size(); i++) {
            if (i > 0) sb.append(" | ");
            sb.append(columnClass).append('.').append(flags.get(i));
        }
        return sb.toString();
    }

    private String referencedConstant(ForeignKeyModel fk) {
        for (TableModel t : model.tables()) {
            if (t.name().equals(fk.referencedTable()) && t.schema().equals(fk.referencedSchema())) {
                return Names.upperSnake(entityNames.get(t));
            }
        }
        return Names.upperSnake(Names.pascal(Names.singular(fk.referencedTable())));
    }

    private static String uniqueName(String base, Set<String> used) {
        String name = base;
        int i = 2;
        while (!used.add(name)) name = base + "_" + i++;
        return name;
    }

    // =========================================================================
    // Row, key, entity, repositories
    // =========================================================================

    private String rowSource(TableModel t, String entity, List<Col> cols) {
        Imports imp = new Imports(config.packageName(), localNames);
        StringBuilder b = new StringBuilder();
        b.append("/**\n * A row of {@code ").append(doc(qualified(t))).append("}.\n *\n");
        for (Col c : cols) b.append(" * @param ").append(c.property()).append(" column {@code ").append(doc(c.model().name())).append("}\n");
        b.append(" */\npublic record ").append(entity).append("Row(");
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) b.append(", ");
            b.append(imp.use(cols.get(i).type().javaType())).append(' ').append(cols.get(i).property());
        }
        b.append(") {\n}\n");
        return file(imp, b);
    }

    private String keySource(TableModel t, String entity, List<Col> cols) {
        Imports imp = new Imports(config.packageName(), localNames);
        StringBuilder b = new StringBuilder();
        b.append("/**\n * The primary key of {@code ").append(doc(qualified(t))).append("}.\n *\n");
        List<Col> keyCols = new ArrayList<>();
        for (String name : t.primaryKey().columns()) keyCols.add(column(cols, name));
        for (Col c : keyCols) b.append(" * @param ").append(c.property()).append(" column {@code ").append(doc(c.model().name())).append("}\n");
        b.append(" */\npublic record ").append(entity).append("Key(");
        for (int i = 0; i < keyCols.size(); i++) {
            if (i > 0) b.append(", ");
            b.append(imp.use(keyCols.get(i).type().javaType())).append(' ').append(keyCols.get(i).property());
        }
        b.append(") {\n}\n");
        return file(imp, b);
    }

    private String keyType(Imports imp, TableModel t, String entity, List<Col> cols) {
        return t.primaryKey().columns().size() == 1
                ? boxed(imp, column(cols, t.primaryKey().columns().get(0)).type().javaType())
                : entity + "Key";
    }

    private String entitySource(TableModel t, String entity, List<Col> cols) {
        Imports imp = new Imports(config.packageName(), localNames);
        String table = entity + "Table";
        String constant = table + "." + naming.tableConstant(t);
        String key = keyType(imp, t, entity, cols);
        String columnClass = imp.use("ch.lxrin.ql.schema.Column");
        StringBuilder b = new StringBuilder();
        b.append("/**\n * An entity of {@code ").append(doc(qualified(t))).append("}: a plain data object that tracks its changes.");
        comment(b, t.comment(), " * ");
        b.append("\n */\npublic class ").append(entity).append(" extends ").append(imp.use("ch.lxrin.ql.entity.Entity")).append('<').append(key).append("> {\n\n");
        for (Col c : cols) b.append("    private ").append(imp.use(c.type().javaType())).append(' ').append(c.property()).append(";\n");
        b.append("\n    /** Creates a new entity; it is inserted by {@code save}. */\n    public ").append(entity).append("() {\n    }\n");
        for (Col c : cols) {
            String type = imp.use(c.type().javaType());
            b.append("\n    /**\n     * Returns column {@code ").append(doc(c.model().name())).append("}.\n     *\n     * @return the value\n     */\n");
            b.append("    public ").append(type).append(' ').append(c.getter()).append("() {\n        return ").append(c.property()).append(";\n    }\n");
            if (!"s".equals(c.model().generated())) {
                b.append("\n    /**\n     * Sets column {@code ").append(doc(c.model().name())).append("}.\n     *\n     * @param ").append(c.property())
                        .append(" the new value\n     */\n");
                b.append("    public void ").append(c.setter()).append('(').append(type).append(' ').append(c.property()).append(") {\n");
                b.append("        this.").append(c.property()).append(" = track(").append(constant).append('.').append(c.constant())
                        .append(", this.").append(c.property()).append(", ").append(c.property()).append(");\n    }\n");
            }
        }
        b.append("\n    @Override\n    public ").append(key).append(" id() {\n        return ");
        if (t.primaryKey().columns().size() == 1) {
            b.append(column(cols, t.primaryKey().columns().get(0)).property());
        } else {
            b.append("new ").append(key).append('(');
            for (int i = 0; i < t.primaryKey().columns().size(); i++) {
                if (i > 0) b.append(", ");
                b.append(column(cols, t.primaryKey().columns().get(i)).property());
            }
            b.append(')');
        }
        b.append(";\n    }\n\n");
        b.append("    @Override\n    public ").append(table).append(" table() {\n        return ").append(constant).append(";\n    }\n\n");
        b.append("    @Override\n    protected Object readValue(").append(columnClass).append("<?> column) {\n        switch (column.name()) {\n");
        for (Col c : cols) {
            b.append("            case \"").append(TypeMapping.escape(c.model().name())).append("\":\n                return ").append(c.property()).append(";\n");
        }
        b.append("            default:\n                throw new IllegalArgumentException(\"unknown column \" + column);\n        }\n    }\n\n");
        b.append("    @Override\n    protected void writeValue(").append(columnClass).append("<?> column, Object value) {\n        switch (column.name()) {\n");
        for (Col c : cols) {
            b.append("            case \"").append(TypeMapping.escape(c.model().name())).append("\":\n                ").append(c.property())
                    .append(" = (").append(imp.use(c.type().javaType())).append(") value;\n                break;\n");
        }
        b.append("            default:\n                throw new IllegalArgumentException(\"unknown column \" + column);\n        }\n    }\n\n");
        String row = entity + "Row";
        b.append("    /**\n     * Returns the current values as a row record.\n     *\n     * @return the row\n     */\n");
        b.append("    public ").append(row).append(" toRow() {\n        return new ").append(row).append('(');
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) b.append(", ");
            b.append(cols.get(i).property());
        }
        b.append(");\n    }\n\n");
        b.append("    /**\n     * Creates a persistent entity from a row, e.g. one read with {@code selectFrom(..)}.\n     *\n")
                .append("     * @param row the row\n     * @return the entity\n     */\n");
        b.append("    public static ").append(entity).append(" fromRow(").append(row).append(" row) {\n        ").append(entity)
                .append(" entity = new ").append(entity).append("();\n        ").append(imp.use("ch.lxrin.ql.entity.EntityAccess"))
                .append(".load(entity, ").append(constant).append(".columns(), new Object[]{");
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) b.append(", ");
            b.append("row.").append(cols.get(i).property()).append("()");
        }
        b.append("});\n        return entity;\n    }\n}\n");
        return file(imp, b);
    }

    private String repositoryBaseSource(TableModel t, String entity, List<Col> cols) {
        Imports imp = new Imports(config.packageName(), localNames);
        String key = keyType(imp, t, entity, cols);
        String table = entity + "Table";
        String constant = table + "." + naming.tableConstant(t);
        String ctx = imp.use("ch.lxrin.ql.runtime.QueryContext");
        StringBuilder b = new StringBuilder();
        b.append("/**\n * The generated part of the repository of {@code ").append(doc(qualified(t)))
                .append("}. Add custom queries to {@link ").append(entity).append("Repository}.\n */\n");
        b.append("public abstract class ").append(entity).append("RepositoryBase extends ").append(imp.use("ch.lxrin.ql.repository.TableRepository"))
                .append('<').append(entity).append(", ").append(key).append(", ").append(entity).append("Row> {\n\n");
        b.append("    /**\n     * Creates the repository.\n     *\n     * @param context the query context\n     */\n");
        b.append("    protected ").append(entity).append("RepositoryBase(").append(ctx).append(" context) {\n        super(context, ")
                .append(constant).append(");\n    }\n\n");
        b.append("    @Override\n    protected ").append(entity).append(" newEntity() {\n        return new ").append(entity).append("();\n    }\n");
        String optional = imp.use("java.util.Optional");
        Set<String> names = new HashSet<>();
        for (KeyModel uk : t.uniqueKeys()) {
            StringBuilder name = new StringBuilder("findBy");
            StringBuilder params = new StringBuilder();
            StringBuilder conditions = new StringBuilder();
            for (int i = 0; i < uk.columns().size(); i++) {
                Col c = column(cols, uk.columns().get(i));
                if (i > 0) {
                    name.append("And");
                    params.append(", ");
                    conditions.append(", ");
                }
                name.append(Character.toUpperCase(c.property().charAt(0))).append(c.property().substring(1));
                params.append(imp.use(c.type().javaType())).append(' ').append(c.property());
                conditions.append(constant).append('.').append(c.constant()).append(".eq(").append(c.property()).append(')');
            }
            if (!names.add(name.toString())) continue;
            b.append("\n    /**\n     * Finds the entity by the unique key {@code ").append(doc(uk.name())).append("}.\n     *\n");
            for (String c : uk.columns()) b.append("     * @param ").append(column(cols, c).property()).append(" the value\n");
            b.append("     * @return the entity, if any\n     */\n");
            b.append("    public ").append(optional).append('<').append(entity).append("> ").append(name).append('(').append(params)
                    .append(") {\n        return findOne(").append(uk.columns().size() == 1 ? conditions
                            : imp.use("ch.lxrin.ql.dsl.Condition") + ".and(" + conditions + ")").append(");\n    }\n");
        }
        b.append("}\n");
        return file(imp, b);
    }

    private String readOnlyBaseSource(TableModel t, String entity) {
        Imports imp = new Imports(config.packageName(), localNames);
        String ctx = imp.use("ch.lxrin.ql.runtime.QueryContext");
        StringBuilder b = new StringBuilder();
        b.append("/**\n * The generated part of the read-only repository of {@code ").append(doc(qualified(t)))
                .append("}. Add custom queries to {@link ").append(entity).append("Repository}.\n */\n");
        b.append("public abstract class ").append(entity).append("RepositoryBase extends ").append(imp.use("ch.lxrin.ql.repository.ReadOnlyRepository"))
                .append('<').append(entity).append("Row> {\n\n");
        b.append("    /**\n     * Creates the repository.\n     *\n     * @param context the query context\n     */\n");
        b.append("    protected ").append(entity).append("RepositoryBase(").append(ctx).append(" context) {\n        super(context, ")
                .append(entity).append("Table.").append(naming.tableConstant(t)).append(");\n    }\n}\n");
        return file(imp, b);
    }

    private void writeStub(String entity, String subject) {
        if (config.repositoryStubDirectory() == null) return;
        Path file = config.repositoryStubDirectory().resolve(config.packageName().replace('.', '/')).resolve(entity + "Repository.java");
        if (Files.exists(file)) return;
        String source = "package " + config.packageName() + ";\n\nimport ch.lxrin.ql.runtime.QueryContext;\n\n"
                + "/**\n * Repository of {@link " + subject + "}. Created once by LxrinQL codegen; add your own queries here.\n */\n"
                + "public class " + entity + "Repository extends " + entity + "RepositoryBase {\n\n"
                + "    /**\n     * Creates the repository.\n     *\n     * @param context the query context\n     */\n"
                + "    public " + entity + "Repository(QueryContext context) {\n        super(context);\n    }\n}\n";
        writeFile(file, source, false);
        stubs.add(file);
    }

    // =========================================================================
    // Enums and Tables
    // =========================================================================

    private List<EnumModel> usedEnums() {
        return model.enums();
    }

    private String enumSource(EnumModel e) {
        Imports imp = new Imports(config.packageName(), localNames);
        String name = naming.enumName(e);
        StringBuilder b = new StringBuilder();
        b.append("/** The PostgreSQL enum type {@code ").append(doc(types.enumSqlName(e))).append("}. */\n");
        b.append("public enum ").append(name).append(" {\n");
        Set<String> used = new HashSet<>();
        for (int i = 0; i < e.labels().size(); i++) {
            String label = e.labels().get(i);
            String constant = uniqueName(Names.javaIdentifier(naming.enumConstant(label)), used);
            b.append("    /** Label {@code ").append(doc(label)).append("}. */\n    ").append(constant).append("(\"").append(TypeMapping.escape(label))
                    .append("\")").append(i == e.labels().size() - 1 ? ";" : ",").append('\n');
        }
        b.append("\n    /** The SQL type. */\n    public static final ").append(imp.use("ch.lxrin.ql.types.DataType")).append('<').append(name)
                .append("> TYPE = ").append(imp.use("ch.lxrin.ql.types.SqlTypes")).append(".pgEnum(\"").append(TypeMapping.escape(types.enumSqlName(e)))
                .append("\", ").append(name).append(".class, ").append(name).append("::label);\n\n");
        b.append("    private final String label;\n\n    ").append(name).append("(String label) {\n        this.label = label;\n    }\n\n");
        b.append("    /**\n     * Returns the database label.\n     *\n     * @return the label\n     */\n");
        b.append("    public String label() {\n        return label;\n    }\n}\n");
        return file(imp, b);
    }

    private String tablesSource() {
        Imports imp = new Imports(config.packageName(), localNames);
        StringBuilder b = new StringBuilder("/** All tables, for {@code import static ").append(config.packageName()).append(".Tables.*}. */\n");
        b.append("public final class Tables {\n\n");
        List<TableModel> sorted = new ArrayList<>(model.tables());
        sorted.sort(Comparator.comparing(naming::tableConstant));
        for (TableModel t : sorted) {
            String cls = entityNames.get(t) + "Table";
            b.append("    /** {@code ").append(doc(qualified(t))).append("} */\n");
            b.append("    public static final ").append(cls).append(' ').append(naming.tableConstant(t)).append(" = ").append(cls).append('.')
                    .append(naming.tableConstant(t)).append(";\n\n");
        }
        b.append("    private Tables() {\n    }\n}\n");
        return file(imp, b);
    }

    // =========================================================================
    // Output helpers
    // =========================================================================

    private String file(Imports imp, StringBuilder body) {
        String resolved = body.toString();
        return HEADER + "package " + config.packageName() + ";\n\n" + imp.block() + resolved;
    }

    private static String resolve(Imports imp, String expression) {
        Matcher m = TYPE_MARKER.matcher(expression);
        StringBuilder sb = new StringBuilder();
        while (m.find()) m.appendReplacement(sb, Matcher.quoteReplacement(imp.use(m.group(1))));
        m.appendTail(sb);
        return sb.toString();
    }

    private static String boxed(Imports imp, String javaType) {
        return imp.use(javaType);
    }

    private String qualified(TableModel t) {
        return t.schema() + "." + t.name();
    }

    private String schemaLiteral(String schema) {
        return schema == null || schema.equals(config.defaultSchema()) ? "null" : "\"" + TypeMapping.escape(schema) + "\"";
    }

    private static void comment(StringBuilder b, String comment, String prefix) {
        if (comment == null || comment.isBlank()) return;
        b.append('\n').append(prefix.stripTrailing()).append('\n');
        for (String line : comment.split("\\R")) b.append(prefix).append(doc(line)).append('\n');
        b.setLength(b.length() - 1);
    }

    /** Escapes text for Javadoc. */
    static String doc(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("*/", "*&#47;")
                .replace("@", "&#64;").replace("{", "&#123;").replace("}", "&#125;");
    }

    private void write(Path dir, String className, String source) {
        writeFile(dir.resolve(className + ".java"), source);
    }

    private void writeFile(Path file, String content) {
        writeFile(file, content, true);
    }

    private void writeFile(Path file, String content, boolean isGenerated) {
        try {
            Files.createDirectories(file.getParent());
            byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
            if (!Files.exists(file) || !java.util.Arrays.equals(Files.readAllBytes(file), bytes)) Files.write(file, bytes);
            if (isGenerated) generated.add(file);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Returns the files of an earlier run (recognised by the header), so stale ones can be removed. */
    private static List<Path> previouslyGenerated(Path dir) {
        List<Path> result = new ArrayList<>();
        if (!Files.isDirectory(dir)) return result;
        try (Stream<Path> files = Files.list(dir)) {
            for (Path f : (Iterable<Path>) files::iterator) {
                if (f.toString().endsWith(".java") && Files.readString(f).startsWith(HEADER)) result.add(f);
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return result;
    }
}
