package ch.lxrin.ql.schema;

import ch.lxrin.ql.dsl.Condition;
import ch.lxrin.ql.dsl.Field;
import ch.lxrin.ql.render.RenderContext;
import ch.lxrin.ql.types.DataType;

import java.util.Objects;

/**
 * A table column with its type and metadata. Columns are created by the
 * generated table classes; the subclasses {@link StringColumn},
 * {@link NumberColumn}, {@link TemporalColumn}, {@link BooleanColumn},
 * {@link JsonColumn} and {@link ArrayColumn} add the operations of their
 * type family.
 *
 * @param <T> the Java type of the column
 */
public class Column<T> implements Field<T> {

    /** The column is {@code NOT NULL}. */
    public static final int NOT_NULL = 1;
    /** The column has a {@code DEFAULT} (including serial columns). */
    public static final int DEFAULT = 1 << 1;
    /** {@code GENERATED BY DEFAULT AS IDENTITY}. */
    public static final int IDENTITY = 1 << 2;
    /** {@code GENERATED ALWAYS AS IDENTITY}. */
    public static final int IDENTITY_ALWAYS = 1 << 3;
    /** A generated column ({@code GENERATED ALWAYS AS (expr) STORED}); never written. */
    public static final int GENERATED = 1 << 4;
    /** Part of the primary key. */
    public static final int PRIMARY_KEY = 1 << 5;

    private final Table<?> table;
    private final String name;
    private final DataType<T> type;
    private final int flags;

    /**
     * Creates a column. Generated code uses the factory methods of {@link Table} instead.
     *
     * @param table the owning table
     * @param name  the SQL column name
     * @param type  the SQL type
     * @param flags a combination of {@link #NOT_NULL}, {@link #DEFAULT}, ...
     */
    protected Column(Table<?> table, String name, DataType<T> type, int flags) {
        this.table = Objects.requireNonNull(table, "table");
        this.name = ch.lxrin.ql.render.Identifiers.requireName(name);
        this.type = Objects.requireNonNull(type, "type");
        this.flags = flags;
    }

    /** Returns the owning table. */
    public Table<?> table() {
        return table;
    }

    /** Returns the SQL column name. */
    @Override
    public String name() {
        return name;
    }

    @Override
    public DataType<T> type() {
        return type;
    }

    /** Returns {@code true} unless the column is {@code NOT NULL}. */
    public boolean nullable() {
        return (flags & NOT_NULL) == 0;
    }

    /** Returns {@code true} if the database supplies a value when none is inserted. */
    public boolean hasDefault() {
        return (flags & (DEFAULT | IDENTITY | IDENTITY_ALWAYS | GENERATED)) != 0;
    }

    /** Returns {@code true} for identity columns. */
    public boolean identity() {
        return (flags & (IDENTITY | IDENTITY_ALWAYS)) != 0;
    }

    /** Returns {@code true} for {@code GENERATED ALWAYS AS IDENTITY} columns. */
    public boolean identityAlways() {
        return (flags & IDENTITY_ALWAYS) != 0;
    }

    /** Returns {@code true} for generated (computed) columns, which can never be written. */
    public boolean generated() {
        return (flags & GENERATED) != 0;
    }

    /** Returns {@code true} if the column belongs to the primary key. */
    public boolean primaryKey() {
        return (flags & PRIMARY_KEY) != 0;
    }

    /** Returns the flags. */
    public int flags() {
        return flags;
    }

    /**
     * {@code this = ?} for a value of unknown static type, checked at runtime.
     * Meant for generic code such as listeners and repositories.
     *
     * @throws IllegalArgumentException if the value does not fit the column type
     */
    public Condition eqUnchecked(Object value) {
        return value == null ? isNull() : eq(type.cast(value));
    }

    @Override
    public void render(RenderContext ctx) {
        if (ctx.qualifyColumns()) ctx.identifier(table.qualifier()).append('.');
        ctx.identifier(name);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Column)) return false;
        Column<?> other = (Column<?>) o;
        return name.equals(other.name) && table.equals(other.table);
    }

    @Override
    public int hashCode() {
        return 31 * table.hashCode() + name.hashCode();
    }

    @Override
    public String toString() {
        return table.qualifier() + "." + name;
    }
}
