package ch.lxrin.ql;

import ch.lxrin.ql.exec.JdbcSqlExecutor;
import ch.lxrin.ql.exec.SqlExecutionException;
import ch.lxrin.ql.exec.SqlExecutor;
import ch.lxrin.ql.query.SelectQuery;
import ch.lxrin.ql.table.Column;
import ch.lxrin.ql.table.TableDef;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import static ch.lxrin.ql.LxrinQL.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Runs generated SQL against a real PostgreSQL database.
 *
 * <p>Enabled only if {@code LXRIN_QL_PG_URL} is set, e.g.
 * {@code jdbc:postgresql://localhost:5432/test?user=postgres&password=secret}.
 * The test creates and drops its own tables.</p>
 */
@EnabledIfEnvironmentVariable(named = "LXRIN_QL_PG_URL", matches = ".+")
class PostgresIntegrationTest {

    static class Customer extends TableDef {
        final Column id = column("id");
        final Column name = column("name");
        final Column email = column("email");
        final Column tags = column("tags");
        final Column profile = column("profile");
        final Column createdAt = column("created_at");

        Customer() {
            super("lq_customer", "c");
        }
    }

    static class Orders extends TableDef {
        final Column id = column("id");
        final Column customerId = column("customer_id");
        final Column total = column("total");
        final Column status = column("status");
        final Column orderedOn = column("ordered_on");

        Orders() {
            super("lq_order", "o");
        }
    }

    public record CustomerTotal(String name, BigDecimal total, long rank) {}

    public static class CustomerBean {
        private Long id;
        private String name;
        private String[] tags;

        public void setId(Long id) { this.id = id; }
        public void setName(String name) { this.name = name; }
        public void setTags(String[] tags) { this.tags = tags; }
    }

    private static Connection connection;
    private static SqlExecutor db;
    private final Customer c = new Customer();
    private final Orders o = new Orders();

    @BeforeAll
    static void connect() throws Exception {
        connection = DriverManager.getConnection(System.getenv("LXRIN_QL_PG_URL"));
        db = JdbcSqlExecutor.forConnection(connection);
        setDefaultExecutor(db);
    }

    @AfterAll
    static void disconnect() throws Exception {
        try (Statement s = connection.createStatement()) {
            s.execute("DROP TABLE IF EXISTS lq_order, lq_customer");
        }
        setDefaultExecutor(null);
        connection.close();
    }

    @BeforeEach
    void schema() throws Exception {
        try (Statement s = connection.createStatement()) {
            s.execute("DROP TABLE IF EXISTS lq_order, lq_customer");
            s.execute("CREATE TABLE lq_customer (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,"
                    + " email text UNIQUE, tags text[] NOT NULL DEFAULT '{}', profile jsonb NOT NULL DEFAULT '{}',"
                    + " created_at timestamptz NOT NULL DEFAULT now())");
            s.execute("CREATE TABLE lq_order (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " customer_id bigint NOT NULL REFERENCES lq_customer(id), total numeric(10,2) NOT NULL,"
                    + " status text NOT NULL, ordered_on date NOT NULL)");
        }
        insertInto(c).columns(c.name, c.email, c.tags, c.profile)
                .values(val("Ada"), val("ada@example.org"), val(new String[]{"vip", "math"}), jsonb(val("{\"city\":\"London\",\"age\":36}")))
                .values(val("Alan"), val("alan@example.org"), val(new String[]{"math"}), jsonb(val("{\"city\":\"Manchester\"}")))
                .values(val("Grace"), val("grace@example.org"), val(new String[0]), jsonb(val("{}")))
                .execute();
        long ada = idOf("Ada");
        long alan = idOf("Alan");
        insertInto(o).columns(o.customerId, o.total, o.status, o.orderedOn)
                .values(ada, new BigDecimal("100.00"), val("PAID"), LocalDate.of(2024, 1, 5))
                .values(ada, new BigDecimal("50.50"), val("PAID"), LocalDate.of(2024, 2, 10))
                .values(ada, new BigDecimal("20.00"), val("OPEN"), LocalDate.of(2024, 2, 11))
                .values(alan, new BigDecimal("75.00"), val("PAID"), LocalDate.of(2024, 3, 1))
                .execute();
    }

    private long idOf(String name) {
        return createContribution(Long.class).select(c.id).from(c).where(eq(c.name, val(name))).single();
    }

    @Test
    void selectWithJoinsGroupingWindowAndRecordMapping() {
        List<CustomerTotal> totals = select(CustomerTotal.class,
                        c.name,
                        coalesce(sum(o.total).filter(eq(o.status, val("PAID"))), inline(0)).as("total"),
                        rank().over(window().orderBy(desc(coalesce(sum(o.total), inline(0))))).as("rank"))
                .from(c)
                .leftJoin(o, eq(o.customerId, c.id))
                .groupBy(c.name)
                .orderBy(inline(3), c.name.asc())
                .multiple();
        assertEquals(3, totals.size());
        assertEquals(new CustomerTotal("Ada", new BigDecimal("150.50"), 1), totals.get(0));
        assertEquals("Grace", totals.get(2).name());
    }

    @Test
    void beanMappingWithArrays() {
        List<CustomerBean> beans = createContribution(CustomerBean.class)
                .select(c.id, c.name, c.tags)
                .from(c)
                .where(contains(c.tags, val(new String[]{"math"})))
                .orderBy(c.name)
                .multiple();
        assertEquals(2, beans.size());
        assertEquals("Ada", beans.get(0).name);
        assertArrayEquals(new String[]{"vip", "math"}, beans.get(0).tags);
        assertNotNull(beans.get(1).id);
    }

    @Test
    void stringDateJsonArrayAndFullTextFunctions() {
        Object[] row = select(
                        upper(c.name), concatWs(" ", c.name, inline("Lovelace")), lpad(c.name, 5, "*"),
                        regexpReplace(c.name, "a", "4", "gi"), splitPart(c.email, "@", 2),
                        jsonGetText(c.profile, "city"), cast(jsonPathText(c.profile, "age"), "int"),
                        cardinality(c.tags), arrayToString(c.tags, "|"),
                        tsMatches(toTsvector("english", c.name), websearchToTsquery("english", val("ada"))),
                        extract("YEAR", dateTrunc("month", val(LocalDate.of(2024, 5, 17)).cast("date"))),
                        toChar(val(LocalDate.of(2024, 5, 17)).cast("date"), "DD.MM.YYYY"),
                        jsonbBuildObject("n", c.name, "t", c.tags),
                        caseWhen(jsonHasKey(c.profile, inline("age")), inline("has age")).otherwise(inline("no age")),
                        md5(c.name), genRandomUuid(), now())
                .from(c)
                .where(eq(c.name, val("Ada")))
                .single();
        assertEquals("ADA", row[0]);
        assertEquals("Ada Lovelace", row[1]);
        assertEquals("**Ada", row[2]);
        assertEquals("4d4", row[3]);
        assertEquals("example.org", row[4]);
        assertEquals("London", row[5]);
        assertEquals(36, row[6]);
        assertEquals(2, row[7]);
        assertEquals("vip|math", row[8]);
        assertEquals(true, row[9]);
        assertEquals(0, new BigDecimal("2024").compareTo((BigDecimal) row[10]));
        assertEquals("17.05.2024", row[11]);
        assertTrue(((String) row[12]).contains("\"n\": \"Ada\""));
        assertEquals("has age", row[13]);
        assertInstanceOf(UUID.class, row[15]);
        assertInstanceOf(OffsetDateTime.class, row[16]);
    }

    @Test
    void cteLateralSetOperationsAndSubqueries() {
        SelectQuery<Object[]> paid = select(o.customerId, sum(o.total).as("total")).from(o)
                .where(eq(o.status, val("PAID"))).groupBy(o.customerId);
        List<String> names = createContribution(String.class)
                .with("paid", paid)
                .select(c.name)
                .from(c)
                .join("paid p", "p.customer_id = c.id")
                .where(gt("p.total", 80))
                .union(select(c.name).from(c).where(notExists(select(inline(1)).from(o).where(eq(o.customerId, c.id)))))
                .orderBy(inline(1))
                .multiple();
        assertEquals(List.of("Ada", "Grace"), names);

        List<Object[]> latest = select(c.name, "lo.total")
                .from(c)
                .leftJoin(lateral(select(o.total).from(o).where(eq(o.customerId, c.id)).orderBy(o.orderedOn.desc()).limit(1).as("lo")))
                .orderBy(c.name)
                .multiple();
        assertEquals(new BigDecimal("20.00"), latest.get(0)[1]);
        assertNull(latest.get(2)[1]);

        assertEquals(1, selectFrom(c).where(in(c.id, select(o.customerId).from(o).where(gt(o.total, 90)))).fetchCount());
        assertTrue(selectFrom(c).where(eq(c.id, any(val(new Long[]{idOf("Alan")})))).fetchExists());
    }

    @Test
    void recursiveCteAndGenerateSeries() {
        List<Integer> numbers = createContribution(Integer.class)
                .withRecursive("t(n)", select(inline(1)).unionAll(select("n + 1").from("t").where(lt("n", inline(5)))))
                .select("n").from("t").multiple();
        assertEquals(List.of(1, 2, 3, 4, 5), numbers);

        List<LocalDate> days = createContribution(LocalDate.class)
                .select(cast("d", "date"))
                .from(generateSeries(cast(val(LocalDate.of(2024, 2, 27)), "date"), cast(val(LocalDate.of(2024, 3, 1)), "date"),
                        interval("1 day")).as("d"))
                .multiple();
        assertEquals(4, days.size());
        assertEquals(LocalDate.of(2024, 2, 29), days.get(2));
    }

    @Test
    void groupingSetsAndPercentiles() {
        List<Object[]> rows = select(o.status, grouping(o.status).as("g"), count().as("n"))
                .from(o).groupBy(rollup(o.status)).orderBy(o.status.asc().nullsLast()).multiple();
        assertEquals(3, rows.size());
        assertEquals(4L, rows.get(2)[2]);

        Double median = createContribution(Double.class)
                .select(percentileCont(0.5).withinGroup(o.total.asc())).from(o).single();
        assertEquals(62.75, median, 0.001);
    }

    @Test
    void insertReturningUpsertUpdateDelete() {
        Long id = insertInto(c).set(c.name, val("Linus")).set(c.email, val("linus@example.org"))
                .returning(c.id).single(Long.class);
        assertNotNull(id);

        int affected = insertInto(c).set(c.name, val("Linus T.")).set(c.email, val("linus@example.org"))
                .onConflict(c.email).doUpdateSetExcluded(c.name).doUpdateWhere(ne(c.name, raw("EXCLUDED.name")))
                .execute();
        assertEquals(1, affected);
        assertEquals(0, insertInto(c).set(c.name, val("X")).set(c.email, val("linus@example.org")).doNothing().execute());
        assertEquals("Linus T.", createContribution(String.class).select(c.name).from(c).where(eq(c.id, id)).single());

        List<Long> updated = update(o).set(o.status, val("CANCELLED")).set(o.total, o.total.times(inline(0)))
                .from(c).where(eq(o.customerId, c.id), eq(c.name, val("Ada")), eq(o.status, val("OPEN")))
                .returning(o.id).multiple(Long.class);
        assertEquals(1, updated.size());

        update(c).set(c.profile, jsonbSet(c.profile, new String[]{"vip"}, jsonb(inline("true")), true))
                .set(c.tags, arrayAppend(c.tags, val("new")))
                .where(eq(c.name, val("Grace"))).execute();
        Object[] grace = select(jsonGetText(c.profile, "vip"), c.tags).from(c).where(eq(c.name, val("Grace"))).single();
        assertEquals("true", grace[0]);
        assertArrayEquals(new String[]{"new"}, (String[]) grace[1]);

        int deleted = deleteFrom(o).using(c).where(eq(o.customerId, c.id), eq(c.name, val("Alan"))).execute();
        assertEquals(1, deleted);

        Long moved = createContribution(Long.class)
                .with("gone", deleteFrom(o).where(eq(o.status, val("CANCELLED"))).returning(o.id))
                .select(count()).from("gone").single();
        assertEquals(1L, moved);
    }

    @Test
    void functionCatalogProducesValidSql() {
        Object t = inline("Hello World");
        Object n = cast(inline(12.345), "numeric");
        Object d = cast(inline("2024-05-17 13:45:00"), "timestamp");
        Object j = jsonb(inline("{\"a\": {\"b\": [1, 2]}, \"k\": null}"));
        Object arr = array(inline(3), inline(1), inline(2));
        Object[] row = select(
                // strings
                length(t), charLength(t), octetLength(t), bitLength(t), lower(t), initcap(t), concat(t, inline("!")),
                substring(t, 1, 5), substringRegex(t, "W[a-z]+"), left(t, 2), right(t, 2), btrim(t, "Hd"), ltrim(t), rtrim(t),
                rpad(t, 12, "."), translate(t, "lo", "01"), strpos(t, inline("World")), startsWith(t, inline("He")), reverse(t),
                repeat(t, 2), stringToArray(t, " "), format("%s|%L", t, t), regexpMatches(t, "o", "g"), regexpSplitToArray(t, "\\s"),
                regexpCount(t, "l"), regexpSubstr(t, "W\\w+"), sha256(convertTo(t, "UTF8")), encode(convertTo(t, "UTF8"), "base64"),
                quoteIdent(t), quoteLiteral(t), quoteNullable(inline(null)), toHex(inline(255)), ascii(t), chr(inline(65)),
                // math
                abs(inline(-1)), ceil(n), floor(n), round(n), round(n, 1), trunc(n), trunc(n, 1), mod(inline(7), inline(3)),
                div(inline(7), inline(3)), power(inline(2), inline(8)), sqrt(inline(16)), cbrt(inline(27)), exp(inline(1)),
                ln(inline(10)), log10(inline(100)), log(inline(2), inline(8)), sign(inline(-3)), pi(), degrees(pi()),
                radians(inline(180)), sin(inline(0)), cos(inline(0)), tan(inline(0)), asin(inline(0)), acos(inline(1)),
                atan(inline(0)), atan2(inline(1), inline(1)), gcd(inline(12), inline(18)), lcm(inline(4), inline(6)),
                widthBucket(inline(5), inline(0), inline(10), 5),
                // date / time
                clockTimestamp(), statementTimestamp(), currentDate(), currentTime(), currentTimestamp(), localTime(),
                localTimestamp(), dateTrunc("day", cast(d, "timestamptz"), "Europe/Zurich"), datePart("dow", d), age(d),
                age(d, d), makeDate(inline(2024), inline(2), inline(29)), makeTime(inline(1), inline(2), inline(3)),
                makeTimestamp(inline(2024), inline(1), inline(1), inline(0), inline(0), inline(0)),
                makeInterval(inline(0), inline(1), inline(0), inline(2), inline(0), inline(0), inline(0)),
                toTimestamp(inline("2024-01-01"), "YYYY-MM-DD"), toTimestamp(inline(0)), toNumber(inline("1,234.5"), "9G999D9"),
                atTimeZone(d, "UTC"), justifyDays(interval("35 days")), justifyHours(interval("27 hours")),
                justifyInterval(interval("-1 mon 5 days")), dateBin("15 minutes", d, cast(inline("2000-01-01"), "timestamp")),
                // ranges
                daterange(cast(inline("2024-01-01"), "date"), cast(inline("2024-02-01"), "date"), "[]"),
                tsrange(d, d), tstzrange(now(), now()), int4range(inline(1), inline(5)), int8range(inline(1), inline(5)),
                numrange(inline(1), inline(5)), isEmpty(int4range(inline(1), inline(1))),
                contains(int4range(inline(1), inline(5)), inline(3)), overlaps(int4range(inline(1), inline(5)), int4range(inline(4), inline(8))),
                // json
                jsonGet(j, "a"), jsonGet(jsonGet(jsonGet(j, "a"), "b"), 0), jsonPath(j, "a", "b"), jsonbPretty(j),
                jsonbTypeof(j), jsonbStripNulls(j), jsonbConcat(j, jsonb(inline("{\"z\": 1}"))), jsonbDelete(j, "k"),
                jsonbDeletePath(j, "a", "b"), jsonbInsert(j, new String[]{"a", "b", "0"}, jsonb(inline("0"))),
                jsonbPathQueryFirst(j, "$.a.b[1]"), jsonbPathQueryArray(j, "$.a.b[*]"), jsonbPathExists(j, "$.a"),
                jsonbPathMatch(j, "exists($.a)"), jsonbArrayLength(jsonPath(j, "a", "b")), jsonBuildObject("x", inline(1)),
                jsonbBuildArray(inline(1), inline("x")), jsonBuildArray(inline(1)), toJson(cast(t, "text")), jsonHasAnyKey(j, array(inline("a"))),
                jsonHasAllKeys(j, array(inline("a"), inline("k"))), jsonb(val("{}")),
                // arrays
                arrayOf(select(inline(1))), arrayElement(arr, 1), arrayLength(arr, 1), arrayPrepend(inline(0), arr),
                arrayCat(arr, arr), arrayRemove(arr, inline(1)), arrayReplace(arr, inline(1), inline(9)),
                arrayPositions(arr, inline(1)), arrayLower(arr, 1), arrayUpper(arr, 1),
                // full-text
                toTsvector(t), toTsquery("english", inline("hello & world")), plaintoTsquery("english", t),
                phrasetoTsquery("english", t), tsRankCd(toTsvector(t), toTsquery(inline("hello"))),
                tsHeadline("english", t, toTsquery(inline("hello"))), setweight(toTsvector(t), "A"),
                // misc
                currentUser(), sessionUser(), currentSchema(), currentDatabase(), version(), pgTypeof(n),
                nullif(inline(1), inline(1)), greatest(inline(1), inline(2)), least(inline(1), inline(2)),
                similarTo(t, inline("%World")), matchesIgnoreCase(t, inline("^hello")), betweenSymmetric(inline(5), inline(10), inline(1)),
                isDistinctFrom(inline(1), null), eq(row(inline(1), inline(2)), row(inline(1), inline(2))))
                .single();
        assertEquals(11, row[0]);
        assertEquals("hello world", row[4]);
        assertEquals("Hello", row[7]);
    }

    @Test
    void aggregateCatalogProducesValidSql() {
        Object[] row = select(count(o.total), countDistinct(o.status), avg(o.total), min(o.total), max(o.total),
                        arrayAgg(o.status).orderBy(o.status), jsonAgg(o.total), jsonObjectAgg(cast(o.id, "text"), o.total),
                        boolAnd(gt(o.total, 0)), boolOr(gt(o.total, 90)), every(gt(o.total, 0)), bitAnd(cast(o.total, "int")),
                        bitOr(cast(o.total, "int")), anyValue(o.status), stddev(o.total), stddevPop(o.total), stddevSamp(o.total),
                        variance(o.total), varPop(o.total), varSamp(o.total), covarPop(o.total, o.id), covarSamp(o.total, o.id),
                        regrSlope(o.total, o.id), regrIntercept(o.total, o.id), percentileDisc(0.5).withinGroup(o.total),
                        mode().withinGroup(o.status), stringAgg(o.status, ",").distinct().orderBy(o.status))
                .from(o).single();
        assertEquals(4L, row[0]);
        assertEquals("OPEN,PAID", row[26]);

        List<Object[]> windows = select(o.id, rowNumber().over(), denseRank().over(window().orderBy(o.total)),
                        percentRank().over(window().orderBy(o.total)), cumeDist().over(window().orderBy(o.total)),
                        ntile(2).over(window().orderBy(o.id)), lag(o.total).over(window().orderBy(o.id)),
                        lead(o.total, 1, inline(0)).over(window().orderBy(o.id)), firstValue(o.total).over(window().orderBy(o.id)),
                        lastValue(o.total).over(window().orderBy(o.id).rowsBetween(unboundedPreceding(), unboundedFollowing())),
                        nthValue(o.total, 2).over(window().orderBy(o.id).rows(unboundedPreceding())))
                .from(o).orderBy(o.id).multiple();
        assertEquals(4, windows.size());
    }

    @Test
    void lockingClausesAreAccepted() {
        assertEquals(1, selectFrom(c).where(eq(c.name, val("Ada"))).forUpdate().of(c).skipLocked().multiple().size());
        assertEquals(3, selectFrom(c).forShare().nowait().multiple().size());
    }

    @Test
    void sqlErrorsAreWrappedWithSql() {
        SqlExecutionException e = assertThrows(SqlExecutionException.class,
                () -> select(raw("no_such_function()")).multiple());
        assertTrue(e.getMessage().contains("no_such_function"));
        assertEquals("42883", e.getSqlState());
    }

    @Test
    void truncateRestartsIdentity() {
        truncate(o, c).restartIdentity().cascade().execute();
        assertEquals(0, selectFrom(c).fetchCount());
    }
}
