package ch.lxrin.ql.it;

import org.postgresql.ds.PGSimpleDataSource;
import org.testcontainers.postgresql.PostgreSQLContainer;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/** One PostgreSQL container for all integration tests of the JVM. */
public final class Postgres {

    private static PostgreSQLContainer container;
    private static PGSimpleDataSource dataSource;

    private Postgres() {}

    /** Returns a data source of the shared container, starting it on first use. */
    public static synchronized DataSource dataSource() {
        if (container == null) {
            container = new PostgreSQLContainer("postgres:17-alpine");
            container.start();
            dataSource = new PGSimpleDataSource();
            dataSource.setUrl(container.getJdbcUrl());
            dataSource.setUser(container.getUsername());
            dataSource.setPassword(container.getPassword());
        }
        return dataSource;
    }

    /** Runs SQL statements (separated by {@code ;} at line ends) outside LxrinQL. */
    public static void execute(String sql) {
        try (Connection con = dataSource().getConnection(); Statement s = con.createStatement()) {
            s.execute(sql);
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }

    /** Recreates the generated test schema ({@code ch.lxrin.ql.it.db}) with the Flyway migrations. */
    public static void migrateItSchema() {
        execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;");
        org.flywaydb.core.Flyway.configure().dataSource(dataSource()).locations("classpath:db/migration").load().migrate();
    }

    /** Creates the schema of {@code ch.lxrin.ql.TestSchema} from scratch. */
    public static void resetTestSchema() {
        execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;\n"
                + "CREATE TYPE role AS ENUM ('ADMIN', 'USER');\n"
                + "CREATE TABLE users (id uuid CONSTRAINT users_pkey PRIMARY KEY, name text NOT NULL, email text NOT NULL,"
                + " role role NOT NULL DEFAULT 'USER', active boolean NOT NULL DEFAULT true,"
                + " created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, tags text[] NOT NULL DEFAULT '{}',"
                + " settings jsonb, version bigint NOT NULL DEFAULT 0, CONSTRAINT users_email_key UNIQUE (email));\n"
                + "CREATE TABLE orders (id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT orders_pkey PRIMARY KEY,"
                + " user_id uuid NOT NULL CONSTRAINT orders_user_id_fkey REFERENCES users(id),"
                + " total numeric(12,2) NOT NULL CONSTRAINT orders_total_check CHECK (total >= 0), status text NOT NULL,"
                + " ordered_on date NOT NULL);\n"
                + "CREATE TABLE audit_log (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, table_name text NOT NULL,"
                + " operation text NOT NULL, row_id text NOT NULL, tx bigint NOT NULL DEFAULT txid_current());");
    }
}
