CREATE TYPE blog_status AS ENUM ('draft', 'published');

CREATE TABLE blog_authors (
    id    uuid PRIMARY KEY,
    name  text NOT NULL,
    email text NOT NULL UNIQUE
);

CREATE TABLE blog_posts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   uuid        NOT NULL REFERENCES blog_authors (id),
    reviewer_id uuid        REFERENCES blog_authors (id),
    title       text        NOT NULL,
    status      blog_status NOT NULL DEFAULT 'draft'
);
