package ch.lxrin.ql.codegen;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/** {@code generateJavadoc} and {@code stubJavadoc}: generated code and stubs with or without comments. */
class JavadocOptionsTest {

    private static final Path GOLDEN = Path.of("src/test/resources/golden-no-javadoc/UserTable.java.txt");

    @TempDir
    Path out;

    private void generate(UnaryOperator<CodegenConfig> configure) {
        CodegenConfig config = configure.apply(GoldenSchema.config(out));
        CodeGenerator.generate(GoldenSchema.model(), config, new DefaultNamingStrategy(config));
    }

    private List<Path> files(String dir) throws IOException {
        try (Stream<Path> s = Files.walk(out.resolve(dir))) {
            return s.filter(p -> p.toString().endsWith(".java")).sorted().collect(Collectors.toList());
        }
    }

    /** Returns the lines of {@code source} that contain a comment, ignoring the generated-file header. */
    private static List<String> commentLines(String source) {
        String body = source.startsWith(CodeGenerator.HEADER) ? source.substring(CodeGenerator.HEADER.length()) : source;
        return body.lines().filter(l -> {
            String t = l.trim();
            return t.startsWith("//") || t.startsWith("/*") || t.startsWith("*") || l.contains("/**") || l.contains("*/");
        }).collect(Collectors.toList());
    }

    @Test
    void withoutJavadocGeneratedCodeAndStubsHaveNoComments() throws IOException {
        generate(c -> c.generateJavadoc(false));
        List<Path> generated = files("java");
        assertEquals(21, generated.size());
        for (Path p : generated) {
            String source = Files.readString(p);
            assertTrue(source.startsWith(CodeGenerator.HEADER + "package com.example.db;\n"), p.toString());
            assertEquals(List.of(), commentLines(source), p.toString());
        }
        List<Path> stubs = files("stubs");
        assertEquals(5, stubs.size());
        for (Path p : stubs) {
            String source = Files.readString(p);
            assertTrue(source.startsWith("package com.example.db;\n"), source);
            assertEquals(List.of(), commentLines(source), p.toString());
        }
        String table = Files.readString(out.resolve("java/com/example/db/UserTable.java"));
        if (Boolean.getBoolean("golden.update")) {
            Files.createDirectories(GOLDEN.getParent());
            Files.writeString(GOLDEN, table);
        }
        assertEquals(Files.readString(GOLDEN), table);
        CodeGeneratorTest.compile(out);
    }

    @Test
    void stubJavadocDefaultsToGenerateJavadocAndCanBeSetSeparately() throws IOException {
        generate(c -> c.generateJavadoc(false).stubJavadoc(true));
        assertEquals(List.of(), commentLines(Files.readString(out.resolve("java/com/example/db/UserTable.java"))));
        String stub = Files.readString(out.resolve("stubs/com/example/db/UserRepository.java"));
        assertTrue(stub.contains("/**\n * Repository of {@link User}."), stub);
        assertFalse(stub.contains("Generated by"), "stubs never get the header");

        Path second = out.resolve("second");
        CodegenConfig config = GoldenSchema.config(second).stubJavadoc(false);
        CodeGenerator.generate(GoldenSchema.model(), config, new DefaultNamingStrategy(config));
        assertTrue(Files.readString(second.resolve("java/com/example/db/UserTable.java")).contains("/** The table without alias. */"));
        String plainStub = Files.readString(second.resolve("stubs/com/example/db/UserRepository.java"));
        assertEquals(List.of(), commentLines(plainStub), plainStub);
        CodeGeneratorTest.compile(second);
    }

    @Test
    void generatedFilesWithoutJavadocAreStillRecognisedAsGenerated() throws IOException {
        generate(c -> c.generateJavadoc(false));
        Path stale = out.resolve("java/com/example/db/GoneTable.java");
        Files.writeString(stale, CodeGenerator.HEADER + "package com.example.db;\n\nclass GoneTable {\n}\n");
        generate(c -> c.generateJavadoc(false));
        assertFalse(Files.exists(stale));
        generate(c -> c);
        assertTrue(Files.readString(out.resolve("java/com/example/db/UserTable.java")).contains("/**"));
    }
}
